spring:
  # Redis Config
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/redis-spring-boot-app
    username: postgres
    password: postgres
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
      validation-query-timeout: 30
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
      id:
        new_generator_mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

springdoc:
  pathsToMatch: /api/**



